const fontSize = {
  "xxxsmall": "0.6rem",
  "xxsmall": "0.8rem",
  "xsmall": "1rem",
  "small": "1.2rem",
  "medium": "1.4rem",
  "large": "1.6rem",
  "xlarge": "1.8rem",
  "xxlarge": "2.4rem"
};

const color = {
  "blackColor": "#000000",
  "whiteColor": "#ffffff",
  "blueColor": "#0000ff",
  "redColor": "#fd0101",
  "grayColor": "#CCCCCC",
  "lightGrayColor": "#D3D3D3",
  "darkGrayColor": "#A9A9A9",
  "lightBlueColor": "#ADD8E6",
  "darkBlueColor": "#00008B",
  "lightRedColor": "#FFA07A",
  "darkRedColor": "#8B0000",
  "greenColor": "#008000",
  "lightGreenColor": "#90EE90",
  "darkGreenColor": "#006400",
  "yellowColor": "#FFFF00",
  "lightYellowColor": "#FFFFE0",
  "darkYellowColor": "#FFD700",
  "orangeColor": "#FFA500",
  "lightOrangeColor": "#FFDAB9",
  "darkOrangeColor": "#FF8C00",
  "pinkColor": "#FFC0CB",
  "lightPinkColor": "#FFB6C1",
  "darkPinkColor": "#FF69B4",
  "brownColor": "#A52A2A",
  "lightBrownColor": "#D2B48C",
  "darkBrownColor": "#8B4513",
  "cyanColor": "#00FFFF",
  "lightCyanColor": "#E0FFFF",
  "darkCyanColor": "#008B8B",
  "magentaColor": "#FF00FF",
  "lightMagentaColor": "#FF77FF",
  "darkMagentaColor": "#8B008B",
  "purpleColor": "#800080",
  "lightPurpleColor": "#D8BFD8",
  "darkPurpleColor": "#4B0082",
  "beigeColor": "#F5F5DC",
  "lightBeigeColor": "#FFF5E1",
  "darkBeigeColor": "#A89B8D",
  "tealColor": "#008080",
  "lightTealColor": "#20B2AA",
  "darkTealColor": "#004D4D",
  "navyColor": "#000080",
  "lightNavyColor": "#4682B4",
  "darkNavyColor": "#000033",
  "oliveColor": "#808000",
  "lightOliveColor": "#BDB76B",
  "darkOliveColor": "#556B2F",
  "coralColor": "#FF7F50",
  "lightCoralColor": "#F08080",
  "darkCoralColor": "#CD5C5C",
  "salmonColor": "#FA8072",
  "lightSalmonColor": "#FFA07A",
  "darkSalmonColor": "#E9967A",
  "khakiColor": "#F0E68C",
  "lightKhakiColor": "#FFFACD",
  "darkKhakiColor": "#BDB76B",
  "goldColor": "#FFD700",
  "lightGoldColor": "#FFFACD",
  "darkGoldColor": "#DAA520"
};

const Theme = {
  fontSize,
  color,
};

export default Theme;
